//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDDongHo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAI_VIET
    {
        public int ID { get; set; }
        public string TEN { get; set; }
        public string HINH { get; set; }
        public string ND_TOMTAT { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<System.DateTime> NGAYDANG { get; set; }
        public string LOAITIN { get; set; }
        public int ID_NGUOIDUNG { get; set; }
        public Nullable<bool> DUYET { get; set; }
    
        public virtual NGUOI_DUNG NGUOI_DUNG { get; set; }
    }
}
