//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDDongHo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_HANG
    {
        public int ID { get; set; }
        public int ID_DONGHO { get; set; }
        public int ID_DONHANG { get; set; }
        public int SOLUONG { get; set; }
        public double DONGIA { get; set; }
        public double GIAGIAM { get; set; }
        public double THANHTIEN { get; set; }
    
        public virtual DONG_HO DONG_HO { get; set; }
        public virtual DON_HANG DON_HANG { get; set; }
    }
}
