//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDDongHo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DON_HANG
    {
        public DON_HANG()
        {
            this.DAT_HANG = new HashSet<DAT_HANG>();
        }
    
        public int ID { get; set; }
        public string SO_DH { get; set; }
        public Nullable<int> ID_KHACHHANG { get; set; }
        public int TONGTIEN { get; set; }
        public string GHICHU { get; set; }
        public Nullable<bool> DUYET { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<System.DateTime> NGAYGIAO { get; set; }
    
        public virtual ICollection<DAT_HANG> DAT_HANG { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
    }
}
