//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDDongHo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONG_HO
    {
        public DONG_HO()
        {
            this.DAT_HANG = new HashSet<DAT_HANG>();
            this.HINH_ANH = new HashSet<HINH_ANH>();
            this.LUOT_LIKE = new HashSet<LUOT_LIKE>();
        }
    
        public int ID { get; set; }
        public string MAUMA { get; set; }
        public Nullable<double> KICHCO { get; set; }
        public Nullable<double> DODAY { get; set; }
        public string CHATLIEU_VO { get; set; }
        public string CHATLIEU_DAY { get; set; }
        public string CHATLIEU_KINH { get; set; }
        public Nullable<int> DOCHIEUNUOC { get; set; }
        public string BAOHANH { get; set; }
        public double DONGIA { get; set; }
        public Nullable<System.DateTime> NGAYDANG { get; set; }
        public Nullable<int> GIAMGIA { get; set; }
        public int ID_HANGSX { get; set; }
        public int ID_KIEUMAY { get; set; }
        public Nullable<bool> MOI { get; set; }
    
        public virtual ICollection<DAT_HANG> DAT_HANG { get; set; }
        public virtual HANG_SX HANG_SX { get; set; }
        public virtual KIEU_MAY KIEU_MAY { get; set; }
        public virtual ICollection<HINH_ANH> HINH_ANH { get; set; }
        public virtual ICollection<LUOT_LIKE> LUOT_LIKE { get; set; }
    }
}
