//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDDongHo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class HANG_SX
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HANG_SX()
        {
            this.DONG_HO = new HashSet<DONG_HO>();
        }
    
        public int ID { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập tên")]
        //[RegularExpression(@"^[A-Z]+[a-zA-Z'\s]*$", ErrorMessage = "Chỉ được nhập chữ")]
        public string TEN { get; set; }
        public string LOGO { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập nội dung giới thiệu")]
        public string GIOITHIEU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONG_HO> DONG_HO { get; set; }
    }
}
