//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDDongHo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANG_SX
    {
        public HANG_SX()
        {
            this.DONG_HO = new HashSet<DONG_HO>();
        }
    
        public int ID { get; set; }
        public string TEN { get; set; }
        public string LOGO { get; set; }
        public string GIOITHIEU { get; set; }
    
        public virtual ICollection<DONG_HO> DONG_HO { get; set; }
    }
}
