//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDDongHo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUOT_LIKE
    {
        public int ID { get; set; }
        public int ID_KHACHHANG { get; set; }
        public int ID_DONGHO { get; set; }
    
        public virtual DONG_HO DONG_HO { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
    }
}
