//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDDongHo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHAN_QUYEN
    {
        public int ID { get; set; }
        public int ID_NGUOIDUNG { get; set; }
        public int ID_QUYENLOI { get; set; }
    
        public virtual NGUOI_DUNG NGUOI_DUNG { get; set; }
        public virtual QUYEN_LOI QUYEN_LOI { get; set; }
    }
}
