//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDDongHo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYEN_LOI
    {
        public QUYEN_LOI()
        {
            this.PHAN_QUYEN = new HashSet<PHAN_QUYEN>();
        }
    
        public int ID { get; set; }
        public string LOAIHINH { get; set; }
        public string NOIDUNG { get; set; }
    
        public virtual ICollection<PHAN_QUYEN> PHAN_QUYEN { get; set; }
    }
}
